### ISSUE TITLE
Uploading multiple files fails

### ISSUE THREAD

**Issue by brenjt** [grabantot/datatransfer-files-promise#1]
When uploading a selections of files instead of a directory the script only returns the first one.

    console.log(dataTransferItems.length)
    for (let item of dataTransferItems) {
        const entry = item.webkitGetAsEntry()
        const newFiles = await getFilesFromEntry(entry)
        console.log(dataTransferItems.length)
        files = files.concat(newFiles)
    }
    console.log(dataTransferItems.length)

The output of this code when I upload 5 files is:

    5
    0
    0

Something with reading the file is causing the `dataTransferItems` to be emptied. I haven't been able to find anything only regarding why it happens.

**Comment by brenjt** [comment]
I found the fix.

    let files = []
    let entries = []

    // Pull out all entries before reading them
    for (let i = 0, ii = dataTransferItems.length; i < ii; i++) {
        entries.push(dataTransferItems[i].webkitGetAsEntry());
    }

    // Recursively read through all entries
    for (let entry of entries) {
        const newFiles = await getFilesFromEntry(entry)
        files = files.concat(newFiles)
    }

Altering the code to the above I was able to drag multiple folders and single files in tandem.

**Comment by hacdias** [comment]
@grabantot why wasn't this fix included in the code?

**Comment by anatol-grabowski** [comment]
@hacdias Sorry. Merged you PR. Nice job.
