### ISSUE TITLE
how to send files object of dropped files after button click

### ISSUE THREAD

**Issue by comsyspro** [grabantot/datatransfer-files-promise#5]
With your code I created a function wich uploads the files directly after the drop event to a php server. But now I want a modification so that firstly you drop the files and after that you press a button which sends the dropped files to the php server. 

I tried several things but the problem is that the localstorage can't store the files object:
-try to store the dropped files object and store it to localStorage.setItem()
-try to created a FormData object and store it to localStorage.setItem()

So how can you access the files object afterwards or how can you let the drop event wait until you press a button? So how to do that?

**Comment by anatol-grabowski** [comment]
I dont think that localStorage can store files. But you can store files in a (global) variable, e.g. window.droppedFiles = files. There is no way to drop files in one browser session and upload them in another session as far as I know.
