### ISSUE TITLE
A URI supplied to the API was malformed, or the resulting Data URL has exceeded the URL length limitations for Data URLs.

### ISSUE THREAD

**Issue by SiddharthaChowdhury** [grabantot/datatransfer-files-promise#6]
Cloned the repo, and executed the index.html, dropped a directory with files inside, and got this - in chrome's developer console

WARNING: 
index.js:9 EncodingError occured within datatransfer-files-promise module
Error message: "A URI supplied to the API was malformed, or the resulting Data URL has exceeded the URL length limitations for Data URLs."
Try serving html over http if currently you are running it from the filesystem.

ERROR:
index.html:17 Uncaught (in promise) DOMException: A URI supplied to the API was malformed, or the resulting Data URL has exceeded the URL length limitations for Data URLs.

**Comment by anatol-grabowski** [comment]
The browser doesn't allow to drop files if the current page is served from file - the URL is malformed - doesn't start with "http://...".
I've added the "Try serving html over http if currently you are running it from the filesystem." message specifically for this case. Please let me know how It can be rephrased to make it more clear.

Use "npm run test" to serve index.html on localhost - this will resolve the problem.
